version: "3.1"
services:
  db:
    image: mysql:8
    env_file:
      - .env.sample
    volumes:
      - ./data:/var/lib/mysql
      # initialization files (sh, sql, sql.gz)
      # - ./db:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
  web:
    image: iamfrisbee/wordpress:latest
    env_file:
      - .env.sample
    volumes:
      # use your own custom htaccess file
      # - ./.htaccess:/var/www/html/.htaccess
      # user your own custom wp-config
      # - ./wp-config.php:/var/www/html/wp-config.php
      - ./themes:/var/www/html/wp-content/themes
      - ./plugins:/var/www/html/wp-content/plugins
      - ./uploads:/var/www/html/wp-content/uploads
      # if you are using a development container
      # mount the root
      - ./:/opt/app
    ports:
      - "8000:8000"
    depends_on:
      - db
