version: "3.1"
services:
  db:
    image: mysql:8.0.19
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=wordpress
      - MYSQL_PASSWORD=changeme
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
    networks:
      - default
  web:
    image: iamfrisbee/wordpress:latest
    environment:
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=wordpress
      - MYSQL_PASSWORD=changeme
    volumes:
      - ./themes:/var/www/html/wp-content/themes
      # - ./plugins:/var/www/html/wp-content/plugins
    ports:
      - "8000:80"
    depends_on:
      - db
    networks:
      - default
